### ISSUE TITLE
Improve support for geographic coordinates

### ISSUE THREAD

**Issue by santisoler** [fatiando/verde#171]
**Description of the desired feature**

Some functions from `verde` are intended to work with both projected and geographic coordinates.
Nevertheless, working with the latter imposes some requirements.
For example, one must ensure continuity around the globe: setting a grid between longitudes 170° and -170° or between 350° and 10° is not possible at the time because numerically the `east` coordinate is lower than the `west` one.
One way to fix this is to add a `latlon=True` argument to those functions in order to make clear that we are passing geographic coordinates.

I'll try to make a complete list of the functions that needs to be enhanced:
- `inside()`
- `grid_coordinates()`
- `scatter_coordinates()`
- `profile_coordinates()`
- `get_region()`
- `pad_region()`

**Are you willing to help implement and maintain this feature?** Yes

**Comment by santisoler** [comment]
@leouieda Can you think more functions that need this enhancement?

**Comment by djhoese** [comment]
I'm not used to using `verde` functions directly (just a fan of the package and its interfaces), but I am dealing with similar issues in pyresample and the geoxarray library (https://github.com/geoxarray/geoxarray/issues/6). I wonder if `units` could be specified instead of a boolean latlon keyword argument. Just an idea.

**Comment by snowman2** [comment]
The pyproj.CRS object has a is_geographic property that is likely useful.

**Comment by leouieda** [comment]
@djhoese I kind of wanted to avoid units in Verde because there are no restrictions on the actual data types that can be used. I like the idea but I don't know if it would be worth the effort of dealing with a unit library to replace the keyword. Are you planning on using that with geoxarray?

@snowman2 that's interesting but I'm not sure how we could use it. The functions above don't really take any CRS arguments right now. So we'd still have to add an argument and pass it around but instead of `latlon=bool` it would be `crs=proj.CRS(...)`. We'll keep this in mind in case there is an added bonus to this, since it would also add a dependency on the pyproj API.

**Comment by leouieda** [comment]
@santisoler I think you could get started with a `latlon` or `geographic` style option in one of those functions.

**Comment by santisoler** [comment]
:+1: I'll add a PR when I start tackling this.
